"""Generate tables

Revision ID: 36a57979bb23
Revises: 76b35f4c764f
Create Date: 2025-06-01 12:22:34.134396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36a57979bb23'
down_revision: Union[str, None] = '76b35f4c764f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leitos') as batch_op:
        batch_op.alter_column(
            'tipo',
            existing_type=sa.VARCHAR(length=10),
            type_=sa.Enum(
                'UTI', 'ENFERMARIA', 'EMERGENCIA', 'ISOLAMENTO',
                'SEMI_INTENSIVO', 'PEDIATRICO', 'NEONATAL', 'PSIQUIATRICO',
                name='tipoleito'
            ),
            existing_nullable=False
        )
        batch_op.alter_column(
            'status',
            existing_type=sa.VARCHAR(length=10),
            type_=sa.Enum(
                'OCUPADO', 'LIVRE', 'RESERVADO', 'EM_MANUTENCAO',
                name='statusleito'
            ),
            existing_nullable=False
        )
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leitos') as batch_op:
        batch_op.alter_column(
            'status',
            existing_type=sa.Enum(
                'OCUPADO', 'LIVRE', 'RESERVADO', 'EM_MANUTENCAO',
                name='statusleito'
            ),
            type_=sa.VARCHAR(length=10),
            existing_nullable=False
        )
        batch_op.alter_column(
            'tipo',
            existing_type=sa.Enum(
                'UTI', 'ENFERMARIA', 'EMERGENCIA', 'ISOLAMENTO',
                'SEMI_INTENSIVO', 'PEDIATRICO', 'NEONATAL', 'PSIQUIATRICO',
                name='tipoleito'
            ),
            type_=sa.VARCHAR(length=10),
            existing_nullable=False
        )
    # ### end Alembic commands ###