"""Generate tables

Revision ID: bc7827844a23
Revises: 8411d3b4e410
Create Date: 2025-05-17 20:49:24.855399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc7827844a23'
down_revision: Union[str, None] = '8411d3b4e410'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estoques',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_item', sa.Enum('MEDICAMENTO', 'INSUMO', 'EQUIPAMENTO', name='tipoitem'), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('unidade', sa.String(length=50), nullable=False),
    sa.Column('data_validade', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leitos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_leito', sa.String(length=10), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('UTI', 'ENFERMARIA', 'EMERGENCIA', 'ISOLAMENTO', 'SEMI_INTENSIVO', 'PEDIATRICO', 'NEONATAL', 'PSIQUIATRICO', name='tipoleito'), nullable=False),
    sa.Column('status', sa.Enum('OCUPADO', 'LIVRE', 'RESERVADO', 'EM_MANUTENCAO', name='statusleito'), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leitos')
    op.drop_table('estoques')
    # ### end Alembic commands ###
